   1  : 1.58,
   0.1: 2.71,
  0.05: 3.84, 
  0.01: 6.63,
 0.005: 7.88, 
 0.001: 10.83

In [35]:
# 2.71 - 1.13

In [2]:
import pandas as pd
import numpy as np
from joblib import dump

from chi import square as cs

In [20]:
data = pd.read_excel("komentar/data_cleanU1.xlsx")
komentar = data.komentar.tolist()
label = data.label.tolist()

# data.tail()

# data = pd.read_excel("komentar/data_uji_1255_bersih.xlsx")
# komentar += data.komentar.tolist()
# label += data.label.tolist()

y = np.array(label)
print(len(y))

5047

# Ekstraksi dan Seleksi Fitur

In [21]:
sf = cs.ChiSquare(alpha = 0.1)
sf.find_best_features(komentar, label, fitur = None)

In [22]:
print("jumlah fitur terbaik:",len(sf.best_features),"dari",len(sf.fitur), "fitur")
best_features = sf.best_features

jumlah fitur terbaik: 2749 dari 15136 fitur

# Pemodelan

## TF-IDF

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(vocabulary = best_features)#
X = vectorizer.fit_transform(komentar)
save = vectorizer.fit(komentar)
dump(save, "model/tfidf.w")
# print(vectorizer.get_feature_names())
fitur = vectorizer.get_feature_names()
print(X.shape)

(5047, 2749)

## Pemodelan MNB

In [24]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

# Pemodelan dan Validasi Model

In [25]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

skf = StratifiedKFold(n_splits=10)
skf.get_n_splits(X, y)

start = 0.001
stop = 1
step = start
alpha_list = np.arange(start,stop+step,step)
# print(alpha_list)
akurasi = list()

ix = 0 #just counter
for alpha in alpha_list:
    clf.set_params(alpha=alpha)
    temp_akurasi = list()
    for train_index, test_index in skf.split(X, y):
    #     print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        #latih model
        clf.fit(X_train,y_train)
        
        #prediksi
        y_pred = clf.predict(X_test)
        temp_akurasi.append(accuracy_score(y_test, y_pred))
    rerata_akurasi = sum(temp_akurasi)/len(temp_akurasi)
    akurasi.append(rerata_akurasi)
#     print('alpha   :',alpha)
#     print('     akurasi :',rerata_akurasi)
#     print("="*100)
    ix +=1
    if ix%100 !=0:
        print(".", end="")
    else:
#         print(alpha, ' | ', rerata_akurasi)
        print("")

        pass

ditt = {
    "alpha":alpha_list,
    "akurasi":akurasi
}
index = akurasi.index(max(akurasi))
acc = pd.DataFrame.from_dict(ditt)
acc

...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................

     alpha   akurasi
0    0.001  0.977040
1    0.002  0.977633
2    0.003  0.977435
3    0.004  0.977435
4    0.005  0.977435
5    0.006  0.977237
6    0.007  0.977237
7    0.008  0.977237
8    0.009  0.977237
9    0.010  0.977039
10   0.011  0.976841
11   0.012  0.976643
12   0.013  0.976643
13   0.014  0.976247
14   0.015  0.976247
15   0.016  0.976247
16   0.017  0.976643
17   0.018  0.976841
18   0.019  0.976643
19   0.020  0.976643
20   0.021  0.976643
21   0.022  0.976643
22   0.023  0.976643
23   0.024  0.976643
24   0.025  0.977039
25   0.026  0.977039
26   0.027  0.977039
27   0.028  0.977039
28   0.029  0.977039
29   0.030  0.977039
..     ...       ...
970  0.971  0.975457
971  0.972  0.975457
972  0.973  0.975457
973  0.974  0.975457
974  0.975  0.975457
975  0.976  0.975457
976  0.977  0.975457
977  0.978  0.975457
978  0.979  0.975457
979  0.980  0.975457
980  0.981  0.975457
981  0.982  0.975457
982  0.983  0.975457
983  0.984  0.975457
984  0.985  0.975457
985  0.986  0.975457
986  0.987  0.975457
987  0.988  0.975457
988  0.989  0.975457
989  0.990  0.975457
990  0.991  0.975457
991  0.992  0.975457
992  0.993  0.975457
993  0.994  0.975457
994  0.995  0.975457
995  0.996  0.975457
996  0.997  0.975457
997  0.998  0.975457
998  0.999  0.975457
999  1.000  0.975457

[1000 rows x 2 columns]

In [26]:
print(alpha_list[index])
print(akurasi[index])

0.002
0.9776331033724489

In [27]:
print(alpha_list[index])
print(akurasi[index])

0.002
0.9776331033724489

# Menyimpan Model

In [29]:
clf.set_params(alpha=alpha_list[index])
clf.fit(X, y)
dump(clf, "model/mnb.m")

['model/mnb.m']

In [15]:
# p = clf.predict(X)

In [30]:
# ditt = {
#     "Prediksi":p,
#     "label":label,
#     "komentar":komentar
# }
# # index = akurasi.index(max(akurasi))
# akk = pd.DataFrame.from_dict(ditt)

In [31]:
# akk.to_excel("coba_.xlsx")